server:
  servlet:
    context-path: /mongodb
  port: 8082

spring:
  application:
    name: persistence-mongodb
  data:
    mongodb:
      uri: mongodb://192.168.56.91:27017/bayern
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect